version: "3.9"
services:
  postgres-database:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "GUIDE_DB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "guide_postgres"
#      PGDATA: "/var/lib/postgresql/data/pgdata-guides"
#    volumes:
#      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"