name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd serverApp
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cd serverApp
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Maven Verify
        run: mvn -B clean verify
