name: guides project jobs

on: [push]

jobs:
  server_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./serverApp
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven test
        run: mvn -B clean test

  fultter_client_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./guide_app
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        with:
          filters: |
            Client:
              - 'guide_app/**'
      if: steps.filter.outputs.Mobile == 'true'
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - name: Codestyle check.
        # TODO add later: --set-exit-if-changed
        run: dart format -o none .
      - name: Analyze the Dart code for any errors.
        run: flutter analyze .
      - name: Run tests.
        run: flutter test
